name: Build and Test

on:
 push:
   branches:
      main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: tsimagnova/demo-app
      IMAGE_TAG: python-app-1.0
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install make
      run: |
        sudo apt-get update
        sudo apt-get install make

    - name: Run Tests
      run: make test
  build_and_push_image:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: tsimagnova/demo-app
      IMAGE_TAG: python-app-1.0
      DOCKER_TLS_CERTDIR: "/certs"

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1  
      - name: Login to Docker Registry
        run: docker login -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PASS }} 

      - name: Build and Push Docker Image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG
  
