name: Build, Test and Deploy

on:
 push:
   branches:
      main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: tsimagnova/demo-app
      IMAGE_TAG: python-app-1.0
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install make
      run: |
        sudo apt-get update
        sudo apt-get install make

    - name: Run Tests
      run: make test
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: tsimagnova/demo-app
      IMAGE_TAG: python-app-1.0
      DOCKER_TLS_CERTDIR: "/certs"

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1  
      - name: Login to Docker Registry
        run: docker login -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PASS }} 

      - name: Build and Push Docker Image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up AWS Key
        run: |
          echo "${{ secrets.SSH_AWS }}" > deploy_key
          chmod 400 deploy_key

      - name: Deploy to Remote Server
        run: |
          ssh -o StrictHostKeyChecking=no -i deploy_key  ubuntu@ec2-18-220-188-109.us-east-2.compute.amazonaws.com "
            docker login -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PASS }} &&
            docker ps -aq | xargs docker stop | xargs docker rm &&
            docker run -d -p 5000:5000 $IMAGE_NAME:$IMAGE_TAG"         
  
